---
title: "Description of the model forms for the equations"
output: rmarkdown::html_vignette
description: |
  Notes on the model forms used in package.
vignette: >
  %\VignetteIndexEntry{Description of the model forms for the equations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Forms of the length-dry biomass allometric equations in `InvAlloR`

Based on an extensive review of the literature of length-dry biomass allometric equations for freshwater invertebrates, there are generally two different model forms that are used to estimate dry biomass from length data.

### Model form 1

The the most common model form in the literature is a power function with a multiplicative error structure (*model1* in the `InvAlloR` package):

$$
Y = a(X^b) \cdot e^\epsilon \tag{Equation-1}
$$

This is the model that is fit when both the Y (i.e. dry biomass) and X (i.e. body size) variables are log-transformed. For example, let's consider taking the natural logarithm of both sides of this equation:

$$
ln(Y) = ln(a) + ln(X^b) + \epsilon \tag{Equation-2}
$$

This equation simplifies to:

$$
ln(Y) = ln(a) + (b \cdot ln(X)) + \epsilon \tag{Equation-3}
$$

This simplified version is the standard linear regression equation. However, given that we fit the model in log-log space with additive error, when we back-transform the error, it is no longer centered on zero. This means that we typically require a correction factor to obtain the appropriate back-transformed Y value (compare Equation 1 with Equation 3).

### Model form 2

The second model form (*model2* in the `InvAlloR` package) is a model that is fit directly using non-linear regression model:

$$
Y = a \cdot (X^b) + \epsilon \tag{Equation-4}
$$

When models are fit using this type of non-linear regression equation, then we do not need any corrections to get the predictions of Y back onto the natural scale.

The vast majority of allometric equations in the literature and in the `InvAlloR` database take the form of *model1*.

## Correction factors for back-transforming log-log models

The `InvAlloR` package automatically implements a range of correction factors to the dry biomass outputs. Here, we detail the various correction factors that are implemented in `InvAlloR`. The specific correction factor used, however, depends on information available for the equation (see details below).

The problems with using log-log models (i.e. *model1* forms) for prediction on the original scale of the response variable are well known (e.g. Marhrlein *et al.* 2016). Models of the form:

$$
Y = a(X^b) \cdot e^\epsilon \tag{Equation-5}
$$
Are typically transformed onto the log-scale as follows:

$$
log(Y) = log(a) + (b \cdot log(X)) + \epsilon \tag{Equation-6}
$$

The problem with this transformation is that the errors become multiplicative and not additive on the log-scale. Thus, predictions of the expected value of Y become the geometric mean rather than the arithmetric mean which is always an underestimation. This means that predictions on the original-scale tend to be biased in such models. How does this bias work mathematically?

When we fit the model on the log-scale, we get the expected value of log(y) given X which is just the fitted model coefficients multiplied by the predictor variables with some additive error.

$$
E(log(Y)|log(X)) = \beta_{fitted} \cdot log(X) + \epsilon \tag{Equation-7}
$$

We, however, want the following: 

$$
E(e^{log(Y)} |log(X)) \tag{Equation-8}
$$

But, if we simply take the exponential of both sides of the equation, we get the following:

$$
e^{E(log(Y)|log(X))} = e^{\beta_{fitted} \cdot log(X) + \epsilon} \tag{Equation-9}
$$

We solve this by taking the expectation of both sides E and after some simplification, we get to:

$$
E(Y|X) = E(e^{\beta_{fitted} \cdot log(X)}) \cdot E(e^{\epsilon}) \tag{Equation-10}
$$
This shows that to get the quantity we want (i.e. E(Y|X)), we need to multiply the model prediction by the expectation of the exponentiated errors.

There are several correction factors that can be used to solve this issue. `InvAlloR` uses three of these correction factors which depend on different sources of information (e.g. model fit: $r^2$, maximimum and minimum y-values, residual mean square and the residuals).

### Duan's smearing factor

The first correction that we use is the standard Duan's smearing factor (Duan 1983, *Journal of the American Statistical Association*). This correction factor requires data on the residuals to calculate and, therefore, it is typically not easy to extract from the literature. However, some papers report it and we directly digitised scatter plots and calculated it for some other equations.

The smearing factor is calculated as:

$$
E(e^{residuals}) \tag{Equation-11}
$$

Or, if using a different logarithm base: 

$$
E(base^{residuals}) \tag{Equation-12}
$$

### Bird and Prairie (1985)

The correction factor proposed by Bird and Prairie (1985, *Journal of Plankton Research*) is to multiply the antilog of the outputted dry biomass on the natural scale by the following correction factor which uses the residual mean square (RMS):

$$
e^{\frac{RMS}{2}} \tag{Equation-13}
$$

Here, $RMS$ is the residual mean square which is the same as the mean squared error (see @sec-mse-rms-rmse section below).

### Strimbu **et al.** (2018)

The vast majority of correction factors to deal with the log-transformation bias rely on knowing the standard deviation of the model residuals. However, when researchers compile equations from the literature, usually they do not have access to the standard deviation of the residuals. This means that the typical correction factors do not work in these cases.

Strimbu *et al.* (2018, *Forestry*) recently proposed a set of correction factors that work when access to the residuals of the model are not available. For `InvAlloR`, we generally only have information on the equation, the range of X values that were used to fit the equation and the coefficient of determination (i.e. the $r^2$ value). Using Strimbu *et al.*'s (2018, *Forestry*) correction factors, this information tends to be sufficient.

Specifically, Strimbu *et al.* (2018, *Forestry*) propose two correction factors that we may be able to use on log-linear equations in our database:

$$
BC3 = e^{(0.5 \cdot (1-r^2)) \cdot  (\frac{1}{log(a)} \cdot \frac{( log_{b=a}(y_{max})-log_{b=a}(y_{max}) )}{6})^2} \tag{Equation-14}
$$

The other correction factor that does not require $r^2$ is:

$$
BC4 = e^{\frac{1}{log(a)^2} \cdot \frac{( log_{b=a}(y_{max})-log_{b=a}(y_{min}) )^2}{72}} \tag{Equation-15}
$$

### MSE, RMS and RMSE {#sec-mse-rms-rmse}

In much of the older literature, there tends to be some confusion about the use of different terms like mean square error, residual mean square and root mean squared error. 

To make sure that this is clear, as far as we can tell, the mean squared error ($MSE$) is calculated in the same way as residual mean square ($RMS$). It appears that $RMS$ is the older term. Nonetheless, it is calculated as:

$$
MSE = \frac{1}{n} \cdot \sum_{i=1}^{n} (y_{i} - \hat{y}_{i}) \tag{Equation-16}
$$

Where $y_i$ is the observed data and $\hat{y}_i$ is the predicted data. Therefore, the $MSE$ (and the $RMS$) is simply the the average of the squared residuals.

Then, if we take the square root of the $RMS$ we get the $RMSE$ which is the root mean squared error. 

$$
RMSE = \sqrt{MSE} \tag{Equation-17}
$$

We generally use the $RMSE$ as the standard deviation of the regression. But, the denominator is not always ($\frac{1}{n}$). It is typically ($\frac{1}{n - K}$) where $k$ is the number of parameters that the model is fit with. Therefore, we can write the standard deviation of the regression ($s$) as:

$$
s = \sqrt{\frac{1}{n-K} \cdot \sum_{i=1}^{n} (y_{i} - \hat{y}_{i})} \tag{Equation-18}
$$

So, given that we are only dealing with models with two parameters, this small difference can probably be ignored and we can use $RMSE$ as a measure of the standard deviation of the model.


## Preservation effects

The recommended approach to generating length-dry biomass equations is to use fresh specimens or frozen specimens (Benke *et al.* 1999, *Journal of the North American Benthological Society*). This is because preservation in commonly used preservatives like formalin and ethanol can cause mass loss as lipids and other compounds may dissolve. 

Loss in dry mass due to preservation can be substantial. For example, Mahrlein *et al.* (2016, *Hydrobiologia*) report dry weight loss of more than 20% due to preservation in ethanol. Similarly, Wetzel *et al.* (2005, *Helgoland Marine Research*) report dry weight loss of more than 30% due to both formalin and ethanol preservation. This is in contrast to the common doctrine that preservation-induced mass loss is less prevalent when animals are preserved in formalin (Leuven *et al.* 1985, *Hydrobiologia*). These numbers (20% or 30%) are significant and, therefore, we should do our best to account for them to the best of our ability.

Generating equations or gathering test data that used different preservation methods can lead to a large additional source of error when estimating dry biomass. However, there is another issue with preservation methods. Usually, we want to estimate dry biomass for communities or species that were collected and preserved. However, individuals that are preserved in ethanol or formalin can also change their lengths. Thus, when these preserved individuals are measured for length, the measured lengths can be incorrect.

We need to look carefully at which preservation methods were used to generate the equation and which preservation is used for the testing data or for the dataset where the length data come from. We have added this information and proposed correction factors for the equations in the equation database. However, given that there are not enough correction factors available in the literature, we have, as of yet, not implemented these corrections into the standard output of `InvAlloR`.






